version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: carloswong1224/kafka-compose:latest
    ports:
      - "10081:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-logs:/kafka/kafka-logs
  db: 
    image: mongo:4.1
    volumes:
      - ./mongodb_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  restapi:
    image: node:10-alpine
    ports:
      - "10080:80"
    working_dir: /home/carlos/src
    volumes:
      - ./restapi_src:/home/carlos/src
    command: npm install && npm run start


