version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: carloswong1224/kafka-compose:latest
    environment:
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-logs:/kafka/kafka-logs
    depends_on:
      - zookeeper

  db: 
    image: mongo:4.0
    volumes:
      - ./mongodb_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  restapi:
    image: node:10-alpine
    ports:
      - "10080:80"
    working_dir: /home/carlos/src
    volumes:
      - ./restapi_src:/home/carlos/src
    command: npm run start
    depends_on:
      - kafka
  kafkaproducer:
    image: node:10-alpine
    working_dir: /home/carlos/src
    volumes:
      - ./restapi_src:/home/carlos/src
    command: npm run producer
    depends_on:
      - kafka




